%--------------------------------------------------------------------------
% PlotBasilarRms.m
%--------------------------------------------------------------------------
%   plots the energy distribution of the output signal after the basilar-
%   membrane filterbank, plotted is the rms (calculated across time) across
%   auditory filters
%
% usage
%   PlotBasilarRms(freq1, IntRep)
%
% input
%   freq1           : center frequencies of basilar-membrane filterbank
%   IntRep          : structure containing data generated by PemoPreProc
%                     resp. CaspPreProc, browse these for details
% version 1.0
%   27/01/2013, C.T. Iben

function PlotBasilarRms(freq1,IntRep)

if nargin < 2, error('not enough input arguments'); end

basilarrms = sqrt(mean(IntRep.BM.^2))';
basilarrmsnorm = basilarrms ./ max(basilarrms);

if length(freq1) == 1
else
    figH3=figure;
    set(figH3,'Name','output basilar-membrane filterbank: energy distribution of x(t) across f_c','NumberTitle','off')
    plot(freq1,basilarrmsnorm,'--o')
    xlabel('auditory filters in Hz')
    ylabel('rms(x(t))/max(rms(x(t)))')
    title('output basilar-membrane filterbank: energy distribution of x(t) across f_c ','Fontweight','bold')
end

%eof