%--------------------------------------------------------------------------
% PlotAdapt.m
%--------------------------------------------------------------------------
% plots the output signal after the adaptation loops, plotted is the amplitude
% in model units across auditory filters across time
%
% usage
%   PlotAdapt(time1, freq1, IntRep)
%
% input
%   time1           : time in seconds
%   freq1           : center frequencies of basilar-membrane filterbank
%   IntRep          : structure containing data generated by PemoPreProc
%                     resp. CaspPreProc, browse these for details
% version 1.0
%   27/01/2013, C.T. Iben

function PlotAdapt(time1,freq1,IntRep)

if nargin < 3, error('not enough input arguments'); end

figH5=figure;
set(figH5,'Name','output adaptation loops','NumberTitle','off')
% two-dimensional if only on-frequency auditory filter is used
if length(freq1) == 1
    plot(time1,IntRep.adapt')
else
    % three-dimensional if multiple auditory filters are used
    mesh(time1,freq1,IntRep.adapt')
    zlabel('model units')
    colorbar
end
xlabel('time in s')
ylabel('auditory filters in Hz')
title('output adaptation loops','Fontweight','bold')

%eof