%--------------------------------------------------------------------------
% PlotBasilar.m
%--------------------------------------------------------------------------
%   plots the output signal after the basilar-membrane filterbank, plotted
%   is amplitude across time
%
% usage
%   PlotBasilar(time1, freq1, IntRep)
%
% input
%   time1           : time in seconds
%   freq1           : center frequencies of basilar-membrane filterbank
%   IntRep          : structure containing data generated by PemoPreProc
%                     resp. CaspPreProc, browse these for details
% version 1.0
%   27/01/2013, C.T. Iben

function PlotBasilar(time1,freq1,IntRep)

if nargin < 3, error('not enough input arguments'); end

figH2=figure;
% two-dimensional if only on-frequency auditory filter is used
if length(freq1) == 1
    plot(time1,IntRep.BM')
else
    % three-dimensional if multiple auditory filters are used
    mesh(time1,freq1,IntRep.BM')
    zlabel('amplitude')
    colorbar
end
xlabel('time in s')
ylabel('auditory filters in Hz')
title('output basilar-membrane filterbank','Fontweight','bold')
set(figH2,'Name','output basilar-membrane filterbank','NumberTitle','off')
%eof