%--------------------------------------------------------------------------
% PlotIntRepImage.m
%--------------------------------------------------------------------------
% plots the two-dimensional internal representation of the input signal,
% plotted is the energy distribution (rms across time) across modulation
% filters across auditory filters, thus only available in multiple auditory
% and modulation filter mode
%
% usage
%   PlotIntRepImage(freq1, freq2, IntRep)
%
% input
%   freq1           : center frequencies of basilar-membrane filterbank
%   freq2           : center frequencies of the modulation filterbank
%   IntRep          : structure containing data generated by PemoPreProc
%                     resp. CaspPreProc, browse these for details
%
% version 1.0
%   27/01/2013, C.T. Iben

function PlotIntRepImage(freq1,freq2,IntRep)

if nargin < 3, error('not enough input arguments'); end

% calculation of rms across time in every auditory and modulation filter
IntRepImage = squeeze(sqrt(mean((IntRep.Y).^2)));
if length(freq1) > 1 && length(freq2) > 1
    figH7=figure;
    set(figH7,'Name','internal representation (energy is color encoded) across f_c and f_m','NumberTitle','off')
    imagesc(IntRepImage')
    colorbar
    axis xy
    set(gca,'XTick',1:3:length(freq1),'XTickLabel',freq1(1:3:end))
    set(gca,'YTick',1:length(freq2),'YTickLabel',freq2)
    xlabel('auditory filters f_c in Hz')
    ylabel('modulation filters f_m in Hz')
    title('internal representation (energy is color encoded) across f_c and f_m','Fontweight','bold')
    %     colorbar
else
    error('illegal plot modus: not available with one auditory or one modulation filter')
end

%eof.m
