%--------------------------------------------------------------------------
% PlotHC.m
%--------------------------------------------------------------------------
%   plots the output signal after the hair cell transformation stage, plotted
%   is amplitude across auditory filters across time
%
% usage
%   PlotHC(time1, freq1, IntRep)
%
% input
%   time1           : time in seconds
%   freq1           : center frequencies of basilar-membrane filterbank
%   IntRep          : structure containing data generated by PemoPreProc
%                     resp. CaspPreProc, browse these for details
% version 1.0
%   27/01/2013, C.T. Iben

function PlotHc(time1,freq1,IntRep)

if nargin < 3, error('not enough input arguments'); end

figH4=figure;
set(figH4,'Name','output hair cell transformation stage','NumberTitle','off')
% two-dimensional if only on-frequency auditory filter is used
if length(freq1) == 1
    plot(time1,IntRep.hc')
else
    % three-dimensional if multiple auditory filters are used
    mesh(time1,freq1,IntRep.hc')
    zlabel('amplitude')
    colorbar
end
xlabel('time in s')
ylabel('auditory filters in Hz')
title('output hair cell transformation stage','Fontweight','bold')
