%--------------------------------------------------------------------------
% PlotIntRep.m
%--------------------------------------------------------------------------
% plots the internal representation of the input signal, several cases
% depending of range of basilar-membrane and modulation filterbank
%
% cases:

%   (1) Internal Representation as in Dau et al., 1996a, Fig.7, p.3619:
%       two-dimensional: one auditory filter (on-freq), one modulation filter (on-freq)
%       plotted are model units across time
%
%   (2) Internal Representation as in Dau et al., 1997a, Fig.6, p.2898:
%       three-dimensional: one auditory filter (on-freq)
%       plotted are model units across modulation filters across time
%
%   (3) Internal Representation, as in (2) but with one modulation filter
%       (on-freq) and multiple auditory filters
%       plotted are model units across auditory filters across time
%
%   (4) Internal Representation with multiple auditory and modulation
%       filters, IntRep is four-dimensional: time-varying activity pattern
%       across auditory and modulation filters,
%       subplot mode per auditory filter, every subplot is an image-plot
%       where model units (color-coded) are plotted across modulation
%       filters across time
%
% usage
%   PlotIntRep(time2, freq1, freq2, IntRep)
%
% input
%   time2           : time in seconds (down-sampled version of time1)
%   freq1           : center frequencies of basilar-membrane filterbank
%   freq2           : center frequencies of the modulation filterbank
%   IntRep          : structure containing data generated by PemoPreProc
%                     resp. CaspPreProc, browse these for details
%
% version 1.0
%   27/01/2013, C.T. Iben

function PlotIntRep(time2,freq1,freq2,IntRep)

if nargin < 4, error('not enough input arguments'); end

%% settings
freq3 = freq2(1:3:end);
time3 = time2(1:floor(length(time2)/4):end);
for i=1:length(time3)
    XTicki{i} = sprintf('%.1f',time3(i));
end
for k = 1:length(freq3)
    YTicki{k}= sprintf('%d',freq3(k));
end
[x1 y1 z1] = size(IntRep.Y);

%% plot

% case (1)
if y1 == 1 && z1 == 1
    figH6a=figure;
    set(figH6a,'Name','internal representation as published in Dau et al. (1996a), Fig.7, p.3619','NumberTitle','off')
    plot(time2,squeeze(IntRep.Y(:,1,1))');
    title('internal representation as published in Dau et al. (1996a), Fig.7, p.3619','Fontweight','bold')
    xlabel('time in s')
    ylabel('model units')
    legend('one auditory filter, one modulation filter')
    
    % case (2)
elseif y1 == 1 && z1 > 1
    figH6b=figure;
    set(figH6b,'Name','internal representation as published in Dau et al. (1997a), Fig.6, p.2898','NumberTitle','off')
    mesh(time2,freq2,squeeze(IntRep.Y(:,1,:))');
    xlabel('time in s')
    ylabel('modulation filters in Hz')
    zlabel('model units')
    colorbar
    title('internal representation as published in Dau et al. (1997a), Fig.6, p.2898','Fontweight','bold')
    
    % case (3)
elseif y1 > 1 && z1 == 1
    figH6c=figure;
    set(figH6c,'Name','internal representation with on-frequency modulation filter','NumberTitle','off')
    mesh(time2,freq1,squeeze(IntRep.Y(:,:,1))');
    xlabel('time in s')
    ylabel('auditory filters in Hz')
    zlabel('model units')
    colorbar
    title('internal representation with on-frequency modulation filter','Fontweight','bold')
    
    % case (4)
else
    B = ceil(sqrt(y1));
    A = ceil(y1 / B);
    cmin = min(min(min(IntRep.Y)));
    cmax = max(max(max(IntRep.Y)));
    figH6d=figure;
    set(figH6d,'Name','two-dimensional internal representation per auditory filter f_c: activity pattern (energy is color encoded) across time t and modulation filters f_m ','NumberTitle','off')
    set(figH6d,'Units','normalized','outerposition',[0 0 1 1])
    for i = 1:y1
        subplot(A,B,i); imagesc(squeeze(IntRep.Y(:,i,:))',[cmin cmax]);
        %         subplot(A,B,i); imagesc(time2,1:length(freq2),squeeze(IntRep.Y(:,i,:))');
        axis xy
        title(sprintf('f_c=%d Hz', freq1(i)));
        if i == 1
            xlabel('time in s','FontWeight','bold')
            ylabel('f_m in Hz','FontWeight','bold')
        end
        set(gca,'XTick',1:floor(length(time2)/4):length(time2),'XTickLabel',XTicki)
        set(gca,'YTick',1:3:length(freq2),'YTickLabel',YTicki)
    end
    subplot(A,B,y1+1)
    set(gca,'CLim',[cmin cmax],'Visible','off')
    colorbar('location','WestOutside')
    axes('Position',[0 0 1 1],'Xlim',[0 1],'Ylim',[0 1],'Box','off','Visible','off','Units','normalized', 'clipping' , 'off');
    text(0.5, 1, 'two-dimensional internal representation per auditory filter f_c: activity pattern (energy is color encoded) across time t and modulation filters f_m ','FontWeight','bold','HorizontalAlignment','center','VerticalAlignment', 'top')
end

%eof
